services:
  web:
    image: nginx:stable-alpine3.21-perl
    ports:
      - "8000:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./.develop/nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - quiz-network
    depends_on:
      php-fpm:
        condition: service_started
  
  php-fpm:
    build: .
    container_name: laravel
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
      - ./.develop/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks: 
      - quiz-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.44-debian
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - quiz-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  adminer:
    image: adminer:fastcgi
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula
    networks:
      - quiz-network
    depends_on:
      - db

networks:
  quiz-network:
    driver: bridge

volumes:
  mysql_data:
